# Generated by Django 5.1.4 on 2024-12-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="firstname",
            field=models.CharField(default="def", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="lastname",
            field=models.CharField(default="fed", max_length=100),
            preserve_default=False,
        ),
    ]
